# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/GivePassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(929, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 40, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(173, 36, 341, 121))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 929, 26))
        self.menubar.setObjectName("menubar")
        self.menuEncrypt = QtWidgets.QMenu(self.menubar)
        self.menuEncrypt.setObjectName("menuEncrypt")
        self.menuDecrypt = QtWidgets.QMenu(self.menubar)
        self.menuDecrypt.setObjectName("menuDecrypt")
        self.menuKey_Encrypt = QtWidgets.QMenu(self.menubar)
        self.menuKey_Encrypt.setObjectName("menuKey_Encrypt")
        self.menuKey_Decrypt = QtWidgets.QMenu(self.menubar)
        self.menuKey_Decrypt.setObjectName("menuKey_Decrypt")
        self.menuStrong_password = QtWidgets.QMenu(self.menubar)
        self.menuStrong_password.setObjectName("menuStrong_password")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuEncrypt.menuAction())
        self.menubar.addAction(self.menuDecrypt.menuAction())
        self.menubar.addAction(self.menuKey_Encrypt.menuAction())
        self.menubar.addAction(self.menuKey_Decrypt.menuAction())
        self.menubar.addAction(self.menuStrong_password.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Give password"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Your strong and secure password"))
        self.menuEncrypt.setTitle(_translate("MainWindow", "Encrypt"))
        self.menuDecrypt.setTitle(_translate("MainWindow", "Decrypt"))
        self.menuKey_Encrypt.setTitle(_translate("MainWindow", "Key Encrypt"))
        self.menuKey_Decrypt.setTitle(_translate("MainWindow", "Key Decrypt"))
        self.menuStrong_password.setTitle(_translate("MainWindow", "Strong password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
